language: csharp
sudo: required

solution: UKPO2.sln

os: 
    - linux


mono:
    - 3.12.0
    
install:
    - mono ./nuget.exe Install-Package TestStack.White -Version 0.13.3 -OutputDirectory WhiteTestDirectory
script:
    - mkdir build
    - cd build
