language: csharp
sudo: required

solution: UKPO2.sln

os: 
    - linux


mono:
    - 3.12.0
    
install:
    - nuget restore UKPO2.sln
    - nuget install TestStack.White -Version 0.13.3 -OutputDirectory WhiteTestDirectory
    - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script: 
    - xbuild /p:Configuration=Debug UKPO2.sln
