language: csharp
sudo: required

solution: UKPO2.sln

os: 
    -linux


mono:
    -latest
    
install:
    -mono ./nuget.exe install TestStack.White -Version latest -OutputDirectory DNAGraphTests
script:
    -mkdir build
    -cd build
